#if !canImport(ObjectiveC)
import XCTest

extension DegreesAndRadiansTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DegreesAndRadiansTests = [
        ("testDegreesToRadians", testDegreesToRadians),
        ("testRadiansToDegrees", testRadiansToDegrees),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DegreesAndRadiansTests.__allTests__DegreesAndRadiansTests),
    ]
}
#endif
