#if !canImport(ObjectiveC)
import XCTest

extension GCDTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GCDTests = [
        ("test380And9820", test380And9820),
        ("test88And983", test88And983),
        ("testOneAndOne", testOneAndOne),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(GCDTests.__allTests__GCDTests),
    ]
}
#endif
